
apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # C'est l'adresse du control-planee
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekkyTWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZXYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZXR1ZGlhbnQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ2NmZjMWU0LWNkN2ItNDRjMi04YWNkLTRlYTY3MTZlOGQ5ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZXY6ZXR1ZGlhbnQtc3J2YWNjb3VudCJ9.jjEw-MWxn_9hNyaHWhpER5ALrMUNjNM8SA-RHKf6pz09OQV0ZGfJT_dhUajcPTVJX0DxYE5o_VOicQguWVSnoyQ7dQpuXBZgrDk-enB444HJeLraXcL56xgy2k8KhwckEL_o3G6wt9y6R5fMFGXc3DDtaOCuU-pD_Ox8-AwHbquSV4-aGVV5MyMm1FzhAGaHZhPW_Pq7KYNXjAKd1PuP36vaE9JzpWT8htgzoAbrgskejzgc8unO3biZBVoi3Gn-nK9HYTXyXtdXMnYUTG9KotR9xOGjShidRTs9QaCsBCpFa94s5p--NPNB-4Gv5zHuZO30pLFuqr4N5afy75HqTQ


contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
